train:
  batch_size: 64
  epochs: 15
  ui: tqdm
  checkpoint_dir: "../../checkpoints/"
  bvp_pipeline: false

data:
  data_dir: "../../data"
  dataset_type: "small"
  downsample_multiplier: 2
  transformation: null
  bvp_agg: "stack"
  amp_pipeline: null
  phase_pipeline: null

encoder:
  dropout: 0.3
  latent_dim: 10
  activation_fn: "relu"

mt:
  decoder_dropout: 0.3
  decoder_activation_fn: "relu"
  predictor_dropout: 0.3
  predictor_activation_fn: "relu"

embed:
  embed_agent_value: "known"
  embed_agent_size: null
  embed_agent_epochs: 1

optim_loss:
  optimizer: "sgd"
  lr: 0.00001
  alpha: 0.5
  beta: 0.5

debug:
  is_debug: false
  on_cpu: false
