train:
  batch_size: 64
  epochs: 15
  ui: tqdm
  checkpoint_dir: "../../checkpoints/"
  bvp_pipeline: false

data:
  data_dir: "../../data"
  dataset_type: "small"
  downsample_multiplier: 2
  transformation: null
  bvp_agg: "stack"
  amp_pipeline: null
  phase_pipeline: null

encoder:
  dropout: 0.3
  latent_dim: 10
  activation_fn: "relu"

mt:
  decoder_dropout: 0.3
  decoder_activation_fn: "relu"
  predictor_dropout: 0.3
  predictor_activation_fn: "relu"

embed:
  value_type: "known"
  embed_size: null
  epochs: 1
  lr: 0.0001
  num_steps: 2048
  anneal_lr: true
  gamma: 0.99
  gae_labmda: 0.95
  norm_advantage: true
  clip_coef: 0.2
  clip_value_loss: true
  entropy_coef: 0.0
  value_func_coef: 0.5
  max_grad_norm: 0.5
  target_kl: null

optim_loss:
  optimizer: "sgd"
  lr: 0.00001
  alpha: 0.5
  beta: 0.5

debug:
  is_debug: false
  on_cpu: false
