train:
  batch_size: 64
  epochs: 2
  ui: "tqdm"
  bvp_pipeline: true

data:
  small_dataset: true
  downsample_multiplier: 2
  bvp_agg: "stack"

encoder:
  latent_dim: 18

optim_loss:
  optimizer: "sgd"

debug:
  is_debug: true
  on_cpu: true
