# Initial attempts to train the model with the known domain agent and BVP as
# input.

train:
  batch_size: 16
  epochs: 300
  ui: tqdm
  checkpoint_dir: "../../checkpoints/"
  bvp_pipeline: true

data:
  data_dir: "../../data"
  dataset_type: "single_domain"
  downsample_multiplier: 2
  transformation: null
  bvp_agg: "sum"
  amp_pipeline: null
  phase_pipeline: null

encoder:
  dropout: 0.3
  latent_dim: 10
  activation_fn: "relu"

mt:
  decoder_dropout: 0.3
  decoder_activation_fn: "relu"
  predictor_dropout: 0.3
  predictor_activation_fn: "relu"

embed:
  embed_agent_value: "known"
  embed_agent_size: null

optim_loss:
  optimizer: "adam"
  lr: 0.0001
  alpha: 0.3
  beta: 0.5

debug:
  is_debug: false
  on_cpu: false
