# Initial attempts to train the model with the known domain agent and csi as
# input.

train:
  batch_size: 16
  epochs: 300
  ui: tqdm
  checkpoint_dir: "../../checkpoints/"

data:
  data_dir: "../../data"
  dataset_type: "single_domain"
  downsample_multiplier: 2
  transformation: "gaf"
  bvp_agg: "sum"
  bvp_pipeline: false
  amp_pipeline:
    - "lowpass_filter"
    - "standard_scalar"
    - "transform"
    - "torch.from_numpy"
  phase_pipeline:
    - "phase_unwrap"
    - "phase_filter"
    - "lowpass_filter"
    - "standard_scalar"
    - "transform"
    - "torch.from_numpy"

encoder:
  dropout: 0.3
  latent_dim: 10
  activation_fn: "relu"
  num_conv_layers: 3
  initial_kernel_size: 5

mt:
  decoder_dropout: 0.3
  decoder_activation_fn: "relu"
  predictor_dropout: 0.3
  predictor_activation_fn: "relu"
  predictor_num_layers: 5

embed:
  value_type: "known"
  embed_size: null

optim_loss:
  optimizer: "adam"
  lr: 0.0001
  alpha: 0.3
  beta: 0.5

debug:
  is_debug: true
  on_cpu: true
  offline: true
