# Initial attempts to train the model with the known domain agent and csi as
# input.

train:
  batch_size: 16
  epochs: 5
  ui: tqdm
  checkpoint_dir: "../../checkpoints/"

data:
  data_dir: "../../data"
  dataset_type: "single_domain"
  downsample_multiplier: 2
  transformation: "gaf"
  bvp_agg: "stack"
  bvp_pipeline: true
  amp_pipeline:
    - "lowpass_filter"
    - "standard_scalar"
    - "transform"
    - "torch.from_numpy"
  phase_pipeline:
    - "phase_unwrap"
    - "phase_filter"
    - "lowpass_filter"
    - "standard_scalar"
    - "transform"
    - "torch.from_numpy"
encoder:
  dropout: 0.3
  latent_dim: 10
  activation_fn: "relu"

mt:
  decoder_dropout: 0.3
  decoder_activation_fn: "relu"
  predictor_dropout: 0.3
  predictor_activation_fn: "relu"

embed:
  value_type: "probability-measure"
  embed_size: 40
  epochs: 2
  start_epoch: 3

optim_loss:
  optimizer: "adam"
  lr: 0.0001
  alpha: 0.3
  beta: 0.5

debug:
  is_debug: true
  on_cpu: true
  offline: true
