data:
  amp_pipeline: null
  bvp_agg: sum
  bvp_pipeline: true
  data_dir: F:\Offline Docs\Master Thesis\data
  dataset_type: single_user_small
  downsample_multiplier: 2
  phase_pipeline: null
  transformation: null
debug:
  is_debug: true
  offline: true
  on_cpu: false
embed:
  actor_dropout: 0.15569374445631912
  actor_num_layers: 5
  anneal_lr: true
  clip_coef: 0.2
  clip_value_loss: true
  critic_dropout: 0.5668692907535556
  critic_num_layers: 3
  embed_size: 50
  entropy_coef: 0.0
  epochs: 1
  gae_lambda: 0.8601225242577095
  gamma: 0.9479217344377912
  lr: 0.0015011966939900698
  max_grad_norm: 0.5
  norm_advantage: true
  start_epoch: 5
  target_kl: null
  value_func_coef: 0.5
  value_type: probability-measure
encoder:
  activation_fn: relu
  dropout: 0.4
  initial_kernel_size: 12
  latent_dim: 90
  num_conv_layers: 6
mt:
  decoder_activation_fn: leaky
  decoder_dropout: 0.30
  predictor_activation_fn: selu
  predictor_dropout: 0.4
  predictor_num_layers: 6
optim_loss:
  alpha: 9.18485309270849e-05
  beta: 0.5
  lr: 0.000184811149339637
  optimizer: adam
train:
  batch_size: 32
  checkpoint_dir: ..\..\checkpoints
  epochs: 300
  ui: tqdm
