data:
  bvp_agg: sum
  bvp_pipeline: 0
  data_dir: ../../data
  dataset_type: single_user_small
  downsample_multiplier: 100
  amp_pipeline:
    - "lowpass_filter"
    - "standard_scalar"
    - "downsample"
    - "transform"
    - "torch.from_numpy"
  phase_pipeline:
    - "phase_unwrap"
    - "phase_filter"
    - "lowpass_filter"
    - "standard_scalar"
    - "downsample"
    - "transform"
    - "torch.from_numpy"
  transformation: gaf
debug:
  is_debug: true
  offline: true
  on_cpu: true
embed:
  agent_type: ddpg
  reward_function: maximize_difference
  start_epoch: 1
  value_type: probability-measure
  epochs: 1
encoder:
  activation_fn: leaky
  dropout: 0.18
  initial_kernel_size: 7
  latent_dim: 60
  num_conv_layers: 3
mt:
  decoder_activation_fn: leaky
  decoder_dropout: 0.26
  predictor_activation_fn: selu
  predictor_dropout: 0.28
  predictor_num_layers: 4
optim_loss:
  alpha: 8.0e-05
  beta: 0.5
  lr: 0.00022
  optimizer: adam
train:
  batch_size: 16
  checkpoint_dir: ../../checkpoints
  epochs: 25
  ui: tqdm
