train:
  batch_size: 4
  epochs: 300
  ui: tqdm
  checkpoint_dir: "../../checkpoints/"

data:
  data_dir: "../../data"
  dataset_type: "single_domain"
  downsample_multiplier: 50
  amp_pipeline:
    - "lowpass_filter"
    - "standard_scalar"
    - "downsample"
    - "transform"
    - "torch.from_numpy"
  phase_pipeline:
    - "phase_unwrap"
    - "phase_filter"
    - "lowpass_filter"
    - "standard_scalar"
    - "downsample"
    - "transform"
    - "torch.from_numpy"
  transformation: rp
  bvp_agg: "sum"
  bvp_pipeline: false

encoder:
  dropout: 0.15
  latent_dim: 50
  activation_fn: "relu"
  initial_kernel_size: 7
  num_conv_layers: 4

mt:
  decoder_dropout: 0.5
  decoder_activation_fn: "selu"
  predictor_dropout: 0.3
  predictor_activation_fn: "leaky"
  predictor_num_layers: 4

embed:
  value_type: "known"
  reward_function: do_nothing
  embed_size: null
  start_epoch: 500

optim_loss:
  optimizer: "adam"
  lr: 0.001
  alpha: 0.00001
  beta: 0.5

debug:
  is_debug: false
  on_cpu: false
  offline: false
