data:
  bvp_agg: sum
  bvp_pipeline: 0
  data_dir: "F:\\Offline Docs\\Master Thesis\\data"
  dataset_type: single_user
  downsample_multiplier: 100
  amp_pipeline:
    - "lowpass_filter"
    - "standard_scalar"
    - "transform"
    - "torch.from_numpy"
  phase_pipeline:
    - "phase_unwrap"
    - "phase_filter"
    - "lowpass_filter"
    - "standard_scalar"
    - "transform"
    - "torch.from_numpy"
  transformation: rp
debug:
  is_debug: false
  offline: false
  on_cpu: false
embed:
  agent_type: ppo
  reward_function: maximize_difference
  start_epoch: 15
  value_type: probability-measure
  epochs: 1
encoder:
  activation_fn: leaky
  dropout: 0.18
  initial_kernel_size: 7
  latent_dim: 60
  num_conv_layers: 3
mt:
  decoder_activation_fn: leaky
  decoder_dropout: 0.26
  predictor_activation_fn: selu
  predictor_dropout: 0.28
  predictor_num_layers: 4
optim_loss:
  alpha: 8.0e-05
  beta: 0.5
  lr: 0.00022
  optimizer: adam
train:
  batch_size: 16
  checkpoint_dir: ../../checkpoints
  epochs: 50
  ui: tqdm
